language: java
jdk: oraclejdk8
sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: mavogel/ilias-client
      branch: master
  - provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: mavogel/ilias-client
      tags: true